#!/usr/bin/env bash
# Resolve and install each image environment into a temporary prefix, then
# write its explicit lock file (envs/<name>.lock, linux-64, with md5s).
# Installing, not only solving, proves the pins are installable (SPEC §13.1).
#
# Usage: envs/make_locks.sh [env ...]     default: all image envs
# Env:   LOCK_TMPDIR  where temporary prefixes go (default: mktemp -d)
#        CONDA        solver binary (default: mamba, else conda)
set -euo pipefail

cd "$(dirname "$0")"
envs=("$@")
[[ ${#envs[@]} -gt 0 ]] || envs=(core quast busco merqury craq)

CONDA=${CONDA:-$(command -v mamba || command -v conda)}
tmp=${LOCK_TMPDIR:-$(mktemp -d)}
mkdir -p "$tmp"

for env in "${envs[@]}"; do
    prefix="$tmp/$env"
    echo "== $env" >&2
    rm -rf "$prefix"
    "$CONDA" env create -q -y -p "$prefix" -f "$env.yaml" >&2
    {
        echo "# Generated by envs/make_locks.sh from $env.yaml. Do not edit."
        "$CONDA" list -p "$prefix" --explicit --md5
    } > "$env.lock"
    rm -rf "$prefix"
    echo "   wrote $env.lock ($(grep -c '^https://' "$env.lock") packages)" >&2
done
