name: tests

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: envs/dev.yaml
          cache-environment: true
      - run: pip install --no-deps --no-build-isolation -e .
      - run: ruff check src tests
      - run: pytest
